#!/usr/bin/bash

echo "test: total round score"
jaq -n '{ round_outcome_score: 7, shape_score: 3}' | \
jaq -cr "$(cat rock-paper-scissors.jq) \"input:\", ., \"total score:\", total_round_score"
echo ""

echo "test: round outcome score"
jaq -n '"lost", "draw", "won" | { round_outcome: . }' | \
jaq -cr "$(cat rock-paper-scissors.jq) [.round_outcome, \" -> \", round_outcome_score | tostring] | add"
echo ""

echo "test: round outcome"
jaq -n '{ ours: "rock", theirs: "scissors" }' | \
jaq -cr "$(cat rock-paper-scissors.jq) [. | tostring, \" -> \", round_outcome] | add"
echo ""
