#!/bin/bash

echo "test: pass"
./verify -t test1 <<< "test 1 approves this message
line 2"
echo ""

echo "test: fails and triggers diff tool"
./verify -t test3 -d diff <<< "test 3 receives this input"
echo ""
