#!/bin/bash

query="$*"

CMDS_AND_RESULTS="[]"

PROMT="
# Task

suggest a command to execute in a bash shell, based on a given request
if more information is needed - construct a command to help get the information
if the command is more than a simple oneliner - only suggest the first step and command to execute this step

# Response format

- only respond with json!
- follow this json structure:
{
    \"thinking\": \"your thinking here\",
    \"exec\": \"pwd\"
}

# Request to execute

$query

# Previous commands and results

$CMDS_AND_RESULTS

"
chat_cmd_response=$(chat "${PROMT}")
thinking=$(echo $chat_cmd_response | jq -r '.thinking')
exec=$(echo $chat_cmd_response | jq -r '.exec')


# Print thinking and exec values
echo thinking:
echo $thinking
echo exec:
echo $exec

# Execute the command
EXEC_RESULT=$(eval $exec 2>&1)
EXEC_EXIT_CODE=$?

echo "EXEC_RESULT: $EXEC_RESULT"
echo "EXEC_EXIT_CODE: $EXEC_EXIT_CODE"

# Add the command and result to the list
CMDS_AND_RESULTS=$(echo $CMDS_AND_RESULTS | jq ". += [{\"cmd\": \"$exec\", \"result\": \"$EXEC_RESULT\" , \"exit_code\": \"$EXEC_EXIT_CODE\"}]")


