#!/bin/bash

MODEL="gpt-4"
API_URL="https://api.openai.com/v1/chat/completions"

USER_MESSAGE="$*"

JSON_SAFE_MESSAGE=$(echo -n "$USER_MESSAGE" | jq -Rs)

# echo $JSON_SAFE_MESSAGE

read -r -d '' PAYLOAD <<- EOM
{
   "model": "$MODEL",
   "messages": [
      {"role": "user", "content": $JSON_SAFE_MESSAGE}
   ]
}
EOM

# echo $PAYLOAD

RESPONSE=$(curl -sS "$API_URL" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  --data "$PAYLOAD")

echo "$RESPONSE" | jq -r '(.choices[0].message.content,.error.message)//empty'
