#!/bin/bash

GIT_DIFF=$(git diff --cached)
# GIT_LOG=$(git log -p -n 11)
# GIT_LOG=$(git log -p -U1 --minimal --word-diff -n 8 | grep -v '\(diff\|index \|Author:\|Date:\)')
GIT_LOG=$(git log --oneline -n 30)

# Export variables so that envsubst can access them
export GIT_DIFF
export GIT_LOG

prompt="$(envsubst < $(dirname "$0")/commit-msg-prompt)"
response="$(chat $prompt)"
if [[ "$response" == *\`\`\`* ]]; then
    # Split to lines, remove the entire lines that contain triple backtick
    response="$(get_code_block.sh <<< "$response")" 
fi
echo "$response" # or any other command to handle the response
